export default [
  {name: "Armillary Sphere"},
  {name: "Ashling the Pilgrim"},
  {name: "Basilisk Collar"},
  {name: "Batterskull"},
  {name: "Blade of the Bloodchief"},
  {name: "Blasphemous Act"},
  {name: "Blinkmoth Urn"},
  {name: "Buried Ruin"},
  {name: "Burning Earth"},
  {name: "Burnished Hart"},
  {name: "Caged Sun"},
  {name: "Champion's Helm"},
  {name: "Chandra's Ignition"},
  {name: "Chandra, Torch of Defiance"},
  {name: "Coercive Portal"},
  {name: "Cryptolith Fragment"},
  {name: "Darksteel Plate"},
  {name: "Dictate of the Twin Gods"},
  {name: "Ensouled Scimitar"},
  {name: "Fire Diamond"},
  {name: "Furnace of Rath"},
  {name: "Gauntlet of Power"},
  {name: "Glacial Chasm"},
  {name: "Godo, Bandit Warlord"},
  {name: "Gratuitous Violence"},
  {name: "Grip of Chaos"},
  {name: "Heartstone"},
  {name: "Hero's Blade"},
  {name: "Inventors' Fair"},
  {name: "Lightning Greaves"},
  {name: "Loxodon Warhammer"},
  {name: "Magebane Armor"},
  {name: "Mana Geyser"},
  {name: "Neko-Te"},
  {name: "Opal Palace"},
  {name: "Orbs of Warding"},
  {name: "Platinum Angel"},
  {name: "Platinum Emperion"},
  {name: "Price of Progress"},
  {name: "Pristine Talisman"},
  {name: "Pyrohemia"},
  {name: "Reforge the Soul"},
  {name: "Relic of Progenitus"},
  {name: "Repercussion"},
  {name: "Ring of Valkas"},
  {name: "Ruby Medallion"},
  {name: "Ruination"},
  {name: "Sculpting Steel"},
  {name: "Scythe of the Wretched"},
  {name: "Sensei's Divining Top"},
  {name: "Shattering Spree"},
  {name: "Shield of Kaldra"},
  {name: "Sol Ring"},
  {name: "Strata Scythe"},
  {name: "Stuffy Doll"},
  {name: "Swiftfoot Boots"},
  {name: "Sword of Kaldra"},
  {name: "Sword of the Animist"},
  {name: "Tenza, Godo's Maul"},
  {name: "Terrain Generator"},
  {name: "Thespian's Stage"},
  {name: "Valakut, the Molten Pinnacle"},
  {name: "Vandalblast"},
  {name: "War's Toll"},
  {name: "Wayfarer's Bauble"},
  {name: "Whispersilk Cloak"},
  {name: "Mountain", quantity: 34}
];
